# Generated by Django 4.1.7 on 2023-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_alter_acessorio_options_alter_veiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
