# Generated by Django 4.1.7 on 2023-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0006_alter_cor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
